### ISSUE TITLE
Unable to import murmur sqlite database in docker container

### ISSUE THREAD

**Issue by LeoVerto** [mumble-voip/grumble#67]
I've mounted a murmur sqlite database into the container and am running `docker-compose run grumble --import-murmurdb /import/mumble.db --cleanup` to import it. When I do that, I get the following error message:

```
panic: sql: unknown driver "sqlite" (forgotten import?)

goroutine 1 [running]:
main.MurmurImport(0x7ffd49818f3e, 0x11, 0xc00017de18, 0x1)
        /go/src/mumble.info/grumble/cmd/grumble/murmurdb.go:45 +0x62f
main.main()
        /go/src/mumble.info/grumble/cmd/grumble/grumble.go:139 +0x767
```

Seems like whatever dependency is required for sqlite is missing in the container.

**Comment by LeoVerto** [comment]
I've managed to get this to somewhat work outside of docker by adding `_ "github.com/mattn/go-sqlite3"` as a dependency and changing `db, err := sql.Open("sqlite", filename)` to `db, err := sql.Open("sqlite3", filename)` and after bypassing the cleanup check (which fails due to the directories not existing) the import seems to work but the server is now stuck in a reboot loop.
